AWSTemplateFormatVersion: '2010-09-09'
Description: A simple CloudFormation template to create an S3 bucket.

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: us-west-2-qatrepo
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: Development
        - Key: Project
          Value: MyProject
